name: Configurable Theme Libraries
type: module
description: Provides the ability to define configurable libraries in your theme which can be configured in theme settings.
core: 8.x
php: 7.1
package: Theming
